# Generated by Django 3.0.4 on 2020-04-10 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='profile/', verbose_name='Image user')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone number')),
                ('is_verified_phone', models.BooleanField(default=False, verbose_name='Verified phone number')),
                ('verification_uuid', models.UUIDField(default=uuid.uuid4, verbose_name='Unique Verification email UUID')),
                ('is_verified_email', models.BooleanField(default=False, verbose_name='Verified email')),
                ('folowers', models.ManyToManyField(related_name='folowers', to=settings.AUTH_USER_MODEL, verbose_name='folower')),
                ('folowing', models.ManyToManyField(related_name='folows', to=settings.AUTH_USER_MODEL, verbose_name='folow')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User_Profile',
                'verbose_name_plural': 'User_Profiles',
            },
        ),
    ]
