# Generated by Django 3.0.4 on 2020-04-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_auto_20200410_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_city',
            field=models.CharField(default=1, max_length=100, verbose_name='Current City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='home_town',
            field=models.CharField(default=1, max_length=100, verbose_name='Home Town'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='relationship',
            field=models.CharField(default=1, max_length=100, verbose_name='Relationship'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='studied',
            field=models.CharField(default=1, max_length=100, verbose_name='Studied'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work',
            field=models.CharField(default=1, max_length=100, verbose_name='Work'),
            preserve_default=False,
        ),
    ]
