# Generated by Django 3.0.4 on 2020-04-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_auto_20200424_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='current_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Current City'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='home_town',
            field=models.CharField(blank=True, max_length=100, verbose_name='Home Town'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='relationship',
            field=models.CharField(blank=True, max_length=100, verbose_name='Relationship'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='studied',
            field=models.CharField(blank=True, max_length=100, verbose_name='Studied'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='work',
            field=models.CharField(blank=True, max_length=100, verbose_name='Work'),
        ),
    ]
