# Generated by Django 3.0.4 on 2020-04-10 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HashtagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name hashtag')),
            ],
            options={
                'verbose_name': 'Hashtag',
                'verbose_name_plural': 'Hashtags',
            },
        ),
        migrations.CreateModel(
            name='PostsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=2000, verbose_name='Text posts')),
                ('date_time_create', models.DateTimeField(auto_now_add=True, verbose_name='Date and time created post')),
                ('likes_count', models.IntegerField(default=0, verbose_name='Likes count')),
                ('comments_count', models.IntegerField(default=0, verbose_name='Comments count')),
                ('hashtag', models.ManyToManyField(related_name='hashtags', to='main.HashtagModel', verbose_name='hashtag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='PostFilesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to='posts/image/<django.db.models.query_utils.DeferredAttribute object at 0x00000191C7C6FAC8>/', verbose_name='File')),
                ('type', models.CharField(max_length=100, verbose_name='Type file')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PostsModel', verbose_name='post')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
    ]
