# Generated by Django 3.0.4 on 2020-04-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200410_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfilesmodel',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Position in post'),
        ),
        migrations.AlterField(
            model_name='postfilesmodel',
            name='file',
            field=models.FileField(max_length=255, upload_to='posts/image/', verbose_name='File'),
        ),
    ]
