# Generated by Django 3.0.4 on 2020-04-16 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_commentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Text')),
                ('date_time_add', models.DateTimeField(auto_now_add=True, verbose_name='Date and time created comment')),
                ('likes_count', models.IntegerField(default=0, verbose_name='Likes count')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PostsModel', verbose_name='post')),
                ('reply_to', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.CommentTestModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
