# Generated by Django 3.0.4 on 2020-04-16 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200416_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenttestmodel',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
