# Generated by Django 3.0.4 on 2020-04-16 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_commenttestmodel_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentTestModel',
        ),
    ]
