# Generated by Django 3.0.4 on 2020-04-21 20:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_postsmodel_page_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='page_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
