# Generated by Django 3.0.4 on 2020-05-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_bookmarks_date_time_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfilesmodel',
            name='video_gif',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='video_gif'),
        ),
    ]
