# Generated by Django 3.0.4 on 2020-05-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_postfilesmodel_video_gif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfilesmodel',
            name='video_gif',
            field=models.ImageField(blank=True, null=True, upload_to='posts/gif/', verbose_name='video_gif'),
        ),
    ]
