# Generated by Django 3.0.4 on 2020-05-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200514_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfilesmodel',
            name='video_gif',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='posts/gif/', verbose_name='video_gif'),
        ),
    ]
