# Generated by Django 3.0.4 on 2020-05-14 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0002_auto_20200514_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchat',
            name='director',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='director', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userchat',
            name='image',
            field=models.ImageField(default=1, upload_to='chats/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userchat',
            name='chat_id',
            field=models.UUIDField(default=uuid.UUID('de5a855b-0a0e-45d5-8a65-767538a9e920')),
        ),
    ]
