# Generated by Django 3.0.4 on 2020-05-14 09:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_auto_20200514_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchat',
            name='chat_id',
            field=models.UUIDField(default=uuid.UUID('58fd659e-8822-4f9e-a000-8ce6197b81d8')),
        ),
        migrations.AlterField(
            model_name='userchat',
            name='image',
            field=models.ImageField(blank=True, upload_to='chats/'),
        ),
    ]
