# Generated by Django 3.0.4 on 2020-05-14 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0004_auto_20200514_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessages',
            name='to_id',
        ),
        migrations.AlterField(
            model_name='userchat',
            name='chat_id',
            field=models.UUIDField(default=uuid.UUID('6413b764-a583-4124-994d-6f9098da3e99')),
        ),
        migrations.AlterField(
            model_name='usermessages',
            name='from_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
