# Generated by Django 3.0.4 on 2020-05-14 10:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_auto_20200514_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessages',
            name='chat_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='messenger.UserChat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userchat',
            name='chat_id',
            field=models.UUIDField(default=uuid.UUID('b3d011b1-c85a-4436-a692-32ef21af5a4c')),
        ),
    ]
