# Generated by Django 3.0.4 on 2020-05-14 17:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_auto_20200514_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchat',
            name='chat_id',
            field=models.UUIDField(default=uuid.UUID('f3801717-11ac-498d-8c35-e61d7b1e7646')),
        ),
    ]
