# Generated by Django 3.0.4 on 2020-05-14 19:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0007_auto_20200514_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchat',
            name='chat_id',
            field=models.UUIDField(default=uuid.UUID('c1e1dda2-1b8c-4e86-8556-9bc0a9529cc9')),
        ),
    ]
