# Generated by Django 3.0.4 on 2020-05-28 05:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0009_auto_20200515_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchat',
            name='chat_id',
            field=models.UUIDField(default=uuid.UUID('82c41371-f88e-4f9d-9308-57917db71c51')),
        ),
    ]
